### ISSUE TITLE
tp-link-3020

### ISSUE THREAD

**Issue by Nzt2** [natirbey/VipCam#1]
Доброго времени суток.
Могли бы вы выложить конфиг для 4мб флешки, по вашему конфигу собираю у меня на 1.8мб больше, а хотелось бы запусть вашу сборку посмотреть что и как работает, заранее спасибо.

**Comment by natirbey** [comment]
Добрый день. К сожалению я могу вам дать только саму прошивку на 3020 (сделать backup). Исходников я не могу найти, т.к. на 3020 мы только пробовали. Из-за 4 мб и перешли на другую плату...В скором будущем хочу выложить образ docker для сборки прошивок, а также образ самой openwrt, чтобы можно было посмотреть на систему на компе.

**Comment by Nzt2** [comment]
Выложите пожалуйста буду благодарен. отправьте на почту vovan125@yandex.ru

**Comment by natirbey** [comment]
Хорошо, в ближайшем будущем.
